package ru.gorshkov.revoluttask.pojo

import com.google.gson.annotations.SerializedName

enum class RevolutCurrency {
    @SerializedName("AUD")
    AUD,
    @SerializedName("BGN")
    BGN,
    @SerializedName("BRL")
    BRL,
    @SerializedName("CAD")
    CAD,
    @SerializedName("CHF")
    CHF,
    @SerializedName("CNY")
    CNY,
    @SerializedName("CZK")
    CZK,
    @SerializedName("DKK")
    DKK,
    @SerializedName("EUR")
    EUR,
    @SerializedName("GBP")
    GBP,
    @SerializedName("HKD")
    HKD,
    @SerializedName("HRK")
    HRK,
    @SerializedName("HUF")
    HUF,
    @SerializedName("IDR")
    IDR,
    @SerializedName("ILS")
    ILS,
    @SerializedName("INR")
    INR,
    @SerializedName("ISK")
    ISK,
    @SerializedName("JPY")
    JPY,
    @SerializedName("KRW")
    KRW,
    @SerializedName("MXN")
    MXN,
    @SerializedName("MYR")
    MYR,
    @SerializedName("NOK")
    NOK,
    @SerializedName("NZD")
    NZD,
    @SerializedName("PHP")
    PHP,
    @SerializedName("PLN")
    PLN,
    @SerializedName("RON")
    RON,
    @SerializedName("RUB")
    RUB,
    @SerializedName("SEK")
    SEK,
    @SerializedName("SGD")
    SGD,
    @SerializedName("THB")
    THB,
    @SerializedName("TRY")
    TRY,
    @SerializedName("USD")
    USD,
    @SerializedName("ZAR")
    ZAR
}